In [ ]:
# ! pip install torch torchvision torchaudio

См. [здесь](https://pytorch.org/get-started/locally/), как установить PyTorch с поддержкой GPU для различных операционных систем.

### Проверяем, что все работает

In [62]:
import torch

In [63]:
print(torch.tensor([1, 2, 3]))

tensor([1, 2, 3])


# Работа с основными объектами PyTorch

Познакомимся с основными объектами в PyTorch: тензоры, оптимизаторы, модули для создания нейросетей, классы для работы с данными.

## Тензоры

По сути, тензоры - это многомерными массивами. Как вы увидите ниже, работа с тезорами в PyTorch очень похожа на работу с numpy-массивами.

In [ ]:
import torch

### Создание тензоров

Создать вектор из данных:

In [64]:
print(torch.tensor([1, 2, 3, 4.5]))

tensor([1.0000, 2.0000, 3.0000, 4.5000])


Создать матрицу из данных:

In [65]:
print(torch.tensor([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])


Создать случайную матрицу:

In [67]:
print(torch.rand(5, 6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


Создать тензор чисел от 0 до 9 включительно:

In [69]:
print(torch.arange(10).reshape(2, 5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Атрибуты тензоров

In [70]:
a = torch.tensor([[1.0, 2, 3],
                  [4, 5, 6]])
print(a)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


Размерность:

In [71]:
print(a.shape)

torch.Size([2, 3])


Тип данных:

In [72]:
print(a.dtype)

torch.float32


Устройство, на котором расположен тензор:

In [75]:
print(a.device)

a.to('meta')

cpu


tensor(..., device='meta', size=(2, 3))

### Преобразования тензоров

In [ ]:
A = torch.rand(2, 6)
print(A)

tensor([[0.1171, 0.8863, 0.0446, 0.2192, 0.6411, 0.4948],
        [0.8207, 0.9852, 0.5989, 0.0891, 0.8761, 0.1901]])


Изменить размерность тензора:

In [ ]:
print(A.reshape(3, 4))

tensor([[0.1171, 0.8863, 0.0446, 0.2192],
        [0.6411, 0.4948, 0.8207, 0.9852],
        [0.5989, 0.0891, 0.8761, 0.1901]])


Превратить тензор в одномерный массив:

In [ ]:
print(A.flatten())

tensor([0.1171, 0.8863, 0.0446, 0.2192, 0.6411, 0.4948, 0.8207, 0.9852, 0.5989,
        0.0891, 0.8761, 0.1901])


Транспонировать матрицу:

In [ ]:
print(A.T)

tensor([[0.1171, 0.8207],
        [0.8863, 0.9852],
        [0.0446, 0.5989],
        [0.2192, 0.0891],
        [0.6411, 0.8761],
        [0.4948, 0.1901]])


Для тензоров более высокой размерности нужно указать, какие измерения переставить.

In [ ]:
print(A.transpose(0, 1))

tensor([[0.1171, 0.8207],
        [0.8863, 0.9852],
        [0.0446, 0.5989],
        [0.2192, 0.0891],
        [0.6411, 0.8761],
        [0.4948, 0.1901]])


### Операции с тензорами одинаковой размерности

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([-1, 0, 1])
A = torch.tensor([[ 0, 1, 2],
                  [-1, 0, 1]])
B = torch.tensor([[1, 2, 3],
                  [7, 0, 5]])
print(a)
print(b)
print(A)
print(B)

tensor([1, 2, 3])
tensor([-1,  0,  1])
tensor([[ 0,  1,  2],
        [-1,  0,  1]])
tensor([[1, 2, 3],
        [7, 0, 5]])


Покомпонентное сложение:

In [ ]:
print(a + b)
print(A + B)

tensor([0, 2, 4])
tensor([[1, 3, 5],
        [6, 0, 6]])


Покомпонентное умножение:

In [ ]:
print(a * b)
print(A * B)

tensor([-1,  0,  3])
tensor([[ 0,  2,  6],
        [-7,  0,  5]])


Покомпонентное возведение в степень:

In [ ]:
print(a**b)
print(A * B)

tensor([1, 1, 3])
tensor([[ 0,  2,  6],
        [-7,  0,  5]])


Скалярное произведение:

In [ ]:
print(a @ b)

tensor(2)


Умножение матрицы на вектор:

In [ ]:
print(A @ a)

tensor([8, 2])


### Операции с тензорами разной размерности

In [ ]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
v_row = torch.tensor([0, 1, 2])
v_col = torch.tensor([[0], [1]])
print(A)
print(v_row)
print(v_col)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([0, 1, 2])
tensor([[0],
        [1]])


Прибавить к каждой строке матрицы один и тот же вектор:

In [ ]:
print(A + v_row)

tensor([[1, 3, 5],
        [4, 6, 8]])


Прибавить к каждому столбцу матрицы один и тот же вектор:

In [ ]:
print(A + v_col)

tensor([[1, 2, 3],
        [5, 6, 7]])


Это частные случаи [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)

### Автоматическое дифференцирование

![image](img/forward_backward.svg)

In [102]:
x = torch.tensor([-1.0, 3.0, -3.0], requires_grad=True)
c = torch.tensor([0.0, 1.0, 2.0], requires_grad=False)
L = torch.sum((x - c)**2)
print(x)
print(c)
print(L)

tensor([-1.,  3., -3.], requires_grad=True)
tensor([0., 1., 2.])
tensor(30., grad_fn=<SumBackward0>)


Считаем градиент переменной `L` по параметрам `x`:

In [103]:
L.backward()

Градиент по `x`:

In [104]:
print(x.grad)

tensor([ -2.,   4., -10.])


Минимизируем `L` методом [градиентного спуска](https://en.wikipedia.org/wiki/Gradient_descent):

In [106]:
optimizer = torch.optim.SGD(params=[x], lr=0.1)

for _ in range(100):
    optimizer.zero_grad()
    L = torch.sum((x - c)**2)
    L.backward()
    optimizer.step()

L = torch.sum((x - c)**2)

print(L, x)

tensor(2.4158e-13, grad_fn=<SumBackward0>) tensor([3.7537e-11, 1.0000e+00, 2.0000e+00], requires_grad=True)


### Упражнение

Найти градиент функции

$$
f(x) = (Ax - b)^2
$$

в точке $x_0 = (1, -1, 0)$, где

$$
A = \begin{pmatrix}
0 & 3 & -1\\
-2 & 2 & 6
\end{pmatrix},
$$

$$
b = \begin{pmatrix}
-1 \\
2
\end{pmatrix}.
$$

Минимизируйте $f$ методом градиентного спуска, укажите полученное значение $x$ и соответствующее значение $f(x)$.

tensor([ 24., -36., -68.])


tensor(1.4211e-14, grad_fn=<SumBackward0>) tensor([ 0.7273, -0.1273,  0.6182], requires_grad=True)


# Работа с torch.nn

В `torch.nn` содержатся компоненты для создания нейросетей (слои, функции потерь, ...).

In [ ]:
import torch.nn as nn

Линейный слой:

In [ ]:
layer = nn.Linear(5, 3)
print(layer(torch.randn(2, 5)))

tensor([[-0.9284,  0.5816, -0.7882],
        [ 0.5818, -0.2041, -0.9308]], grad_fn=<AddmmBackward0>)


Функция активации `ReLU`:

In [ ]:
layer = nn.ReLU()
print(layer(torch.tensor([[-1.0, 1.0, 2.0, 3.0, -5.0]])))

tensor([[0., 1., 2., 3., 0.]])


Слой `Dropout`:

In [112]:
layer = nn.Dropout(0.5)
print(layer(torch.tensor([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], dtype=torch.float)))

tensor([[20.,  0.,  0.,  0., 28., 30., 32.,  0., 36., 38., 40.]])


Объединяем всё в один пайплайн:

In [ ]:
layer = nn.Sequential(
    nn.Linear(5, 3),
    nn.ReLU(),
    nn.Dropout(0.5)
)
print(layer(torch.randn((2, 5))))

tensor([[0.0000, 0.0000, 0.2690],
        [0.0000, 0.0000, 0.3268]], grad_fn=<MulBackward0>)


Реализовать свой модуль можно следующим образом:
1) Создать производный от `nn.Module` класс.
2) В методе `__init__` вызвать этот же метод базового класса и определить необходимые элементы.
3) Определить метод `forward` (вычисление итогового результата).

Для примера создадим простую нейросеть, решающую задачу регрессии.

In [ ]:
class RegressionModel(nn.Module):
    def __init__(self, n_inputs):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(n_inputs, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(64, 1)
        )

    def forward(self, x):
        res = self.model(x)
        return res

Создаем нейросеть со случайно инициализированными весами:

In [113]:
model = RegressionModel(n_inputs=3)
print(model)

RegressionModel(
  (model): Sequential(
    (0): Linear(in_features=3, out_features=128, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=128, out_features=64, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.5, inplace=False)
    (6): Linear(in_features=64, out_features=1, bias=True)
  )
)


Применяем нейросеть к случайным входам:

In [114]:
inputs = torch.randn((16, 3))
outputs = model(inputs)
print(inputs)
print(outputs)

tensor([[ 0.5277, -0.1454, -1.2570],
        [ 0.4603,  0.2929, -0.9040],
        [ 3.0752,  2.2212, -0.7921],
        [ 0.1431,  0.1196,  0.1512],
        [-0.4875, -1.0465, -1.5815],
        [ 0.1947, -0.1793,  0.6254],
        [-0.4938, -0.2869,  1.1564],
        [ 1.1438, -1.2116,  0.6960],
        [-0.9580, -0.0296, -0.0765],
        [ 0.6090,  0.8991, -1.5046],
        [ 1.0583,  0.5592,  1.4971],
        [ 0.1307,  0.6695, -0.0471],
        [-0.8030,  0.9306, -1.0326],
        [ 0.2099, -0.9337, -1.3468],
        [-0.5099, -0.1163, -1.0048],
        [-0.0383,  0.0115, -0.8755]])
tensor([[ 0.0176],
        [-0.0426],
        [-0.2177],
        [ 0.0596],
        [-0.4645],
        [-0.0426],
        [ 0.0076],
        [ 0.2612],
        [-0.0301],
        [ 0.1194],
        [-0.0994],
        [-0.1597],
        [ 0.2677],
        [-0.3470],
        [-0.0904],
        [-0.4098]], grad_fn=<AddmmBackward0>)


### Упражнение

Реализовать нейросеть, которая решает многоклассовую задачу классификации.

In [130]:
class ClassificationModel(nn.Module):
    def __init__(self, n_inputs, n_outputs):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(n_inputs, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(64, n_outputs)
        )

    def forward(self, x):
        res = self.model(x)
        return res

In [ ]:
model = ClassificationModel(n_inputs=3, n_outputs=5)
print(model)

In [ ]:
inputs = torch.randn((16, 3))
outputs = model(inputs)
print(inputs)
print(outputs)

tensor([[-0.5209, -0.4240, -1.5090],
        [ 1.2582,  0.8365,  0.4827],
        [ 0.8861, -0.8171, -0.0058],
        [ 0.0523, -0.9964,  0.2052],
        [ 1.0111,  0.1694,  0.5641],
        [-0.7087,  0.5506,  1.4862],
        [-0.7013, -1.4389,  0.3379],
        [-0.8933,  0.4242, -1.0964],
        [ 1.0608,  1.2595, -0.2426],
        [ 0.8870,  1.3541, -0.3570],
        [ 0.6675, -0.5566, -0.8818],
        [-1.0259, -1.6939, -1.2858],
        [ 0.4243, -0.7593, -0.5592],
        [ 0.7191, -0.6744, -0.7800],
        [-0.1180, -0.0104, -0.0098],
        [ 0.7699, -0.5383, -0.5641]])
tensor([[-0.4924, -0.0169,  0.2994, -0.3879, -0.1447],
        [-0.2704,  0.7011,  0.7769, -0.5781,  0.0221],
        [-0.0596,  0.1705,  0.0792, -0.2325, -0.2036],
        [ 0.3744,  0.3776,  0.0795, -0.2564, -0.1554],
        [-0.0979,  0.2576,  0.0606, -0.2082, -0.1200],
        [ 0.0669,  1.0411,  0.8262, -0.4135, -0.3432],
        [-0.2700,  0.1828,  0.2291, -0.2263,  0.2018],
        [-0.0484,  0.3

# Работа с данными

In [115]:
import pandas as pd
import numpy as np

Загрузим классический датасет ["Ирисы Фишера"](https://en.wikipedia.org/wiki/Iris_flower_data_set)

In [116]:
df = pd.read_csv('Iris.csv').sample(frac=1, random_state=42, ignore_index=True)
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   74            6.1           2.8            4.7           1.2   
1   19            5.7           3.8            1.7           0.3   
2  119            7.7           2.6            6.9           2.3   
3   79            6.0           2.9            4.5           1.5   
4   77            6.8           2.8            4.8           1.4   

           Species  
0  Iris-versicolor  
1      Iris-setosa  
2   Iris-virginica  
3  Iris-versicolor  
4  Iris-versicolor

Размеры датасета:

In [ ]:
print(df.shape)

(150, 6)


Распределение классов:

In [ ]:
df['Species'].value_counts()

Species
Iris-versicolor    50
Iris-setosa        50
Iris-virginica     50
Name: count, dtype: int64

Получим матрицу признаков `X` и вектор ответов `y`. При обучении мы можем оперировать только с числами, поэтому закодируем каждый класс числом (0, 1, 2).

In [ ]:
def preprocess(df):
    X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values.astype(np.float32)
    y = df['Species'].map({'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}).values
    return X, y

In [ ]:
X, y = preprocess(df)
X_train, y_train = X[:50], y[:50]
X_valid, y_valid = X[50:100], y[50:100]
X_test, y_test = X[100:150], y[100:150]

In [ ]:
print(X[0], y[0])

[6.1 2.8 4.7 1.2] 1


Для того, чтобы удобно обучать нейросети с помощью PyTorch, в нем реализованы два класса работы с данными: `Dataset`, `DataLoader`.

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class MyDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

    def __len__(self):
        return len(self.X)

In [ ]:
train_dataset = MyDataset(X_train, y_train)
valid_dataset = MyDataset(X_valid, y_valid)
test_dataset = MyDataset(X_test, y_test)

Посмотрим, что можно делать с датасетами. Мы можем получить его размер с помощью len(...). Для этого мы реализовали метод `__len__`:

In [ ]:
print(len(train_dataset))

50


Мы также можем обращаться к массиву, используя различные виды индексирования:

In [ ]:
x, y = train_dataset[0]
print(x, y)

[6.1 2.8 4.7 1.2] 1


In [ ]:
X_batch, y_batch = train_dataset[:5]
print(X_batch)
print(y_batch)

[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]]
[1 0 2 1 1]


In [ ]:
X_batch, y_batch = train_dataset[[0, 2, 5]]
print(X_batch)
print(y_batch)

[[6.1 2.8 4.7 1.2]
 [7.7 2.6 6.9 2.3]
 [5.4 3.4 1.5 0.4]]
[1 2 0]


Класс `DataLoader` нужен для автоматического формирования батчей для заданного датасета.

In [ ]:
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True, drop_last=True)
valid_loader = DataLoader(valid_dataset, batch_size=8, shuffle=True, drop_last=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=True, drop_last=True)

In [ ]:
batches = [x for x in train_loader]
print(len(batches))
print(batches[0])
print(batches[1])

6
[tensor([[6.6000, 3.0000, 4.4000, 1.4000],
        [7.7000, 2.6000, 6.9000, 2.3000],
        [6.0000, 2.9000, 4.5000, 1.5000],
        [5.7000, 4.4000, 1.5000, 0.4000],
        [6.2000, 2.2000, 4.5000, 1.5000],
        [6.5000, 3.0000, 5.8000, 2.2000],
        [6.1000, 3.0000, 4.9000, 1.8000],
        [5.2000, 4.1000, 1.5000, 0.1000]]), tensor([1, 2, 1, 0, 1, 2, 2, 0])]
[tensor([[6.3000, 2.5000, 5.0000, 1.9000],
        [6.4000, 3.1000, 5.5000, 1.8000],
        [4.8000, 3.1000, 1.6000, 0.2000],
        [6.4000, 2.8000, 5.6000, 2.1000],
        [6.1000, 2.8000, 4.7000, 1.2000],
        [5.5000, 2.4000, 3.7000, 1.0000],
        [5.1000, 3.8000, 1.5000, 0.3000],
        [5.0000, 3.6000, 1.4000, 0.2000]]), tensor([2, 2, 0, 2, 1, 1, 0, 0])]


# Обучение модели

In [ ]:
import random
import numpy as np
from tqdm import tqdm

Сделаем эксперименты воспроизводимыми

In [ ]:
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

Зададим параметры обучения

In [128]:
# Количество эпох (полных проходов по датасету)
n_epochs = 128

# Размерность входа
n_inputs = 4

# Размерность выхода (кол-во классов)
n_outputs = 3

# Скорость обучения (learning rate)
lr = 1e-3

Инициализируем модель, функцию потерь и оптимизатор

In [131]:
model = ClassificationModel(n_inputs=n_inputs, n_outputs=n_outputs)
loss_func = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params=model.parameters(), lr=lr)

Реализуем вычисление потерь на валидационном датасете

In [132]:
model.training

True

In [133]:
def compute_validation_loss(model, loader, loss_func):
    loss = 0
    model.eval()
    for x, y in loader:
        with torch.no_grad():
            logits = model(x)
        loss += loss_func(logits, y).item() / len(loader)
    return loss

Реализуем цикл обучения нейросети (внешний цикл по эпохам, а внутренний -- по батчам). В конце каждой эпохи будем считать потери на валидационном датасете.

In [134]:
for i in range(1, n_epochs + 1):
    print(f'Epoch {i}')
    for x, y in tqdm(train_loader):
        logits = model(x)
        loss = loss_func(logits, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    eval_loss = compute_validation_loss(model, valid_loader, loss_func)
    print(f'train_loss={loss.item()}, eval_loss={eval_loss}')

Epoch 1


100%|██████████| 6/6 [00:00<00:00, 61.31it/s]


train_loss=1.3773870468139648, eval_loss=1.0775188604990642
Epoch 2


100%|██████████| 6/6 [00:00<00:00, 470.66it/s]


train_loss=0.9769901037216187, eval_loss=0.9859365920225778
Epoch 3


100%|██████████| 6/6 [00:00<00:00, 493.35it/s]


train_loss=0.9205216765403748, eval_loss=0.9081339836120607
Epoch 4


100%|██████████| 6/6 [00:00<00:00, 513.55it/s]


train_loss=0.7787574529647827, eval_loss=0.8342000047365824
Epoch 5


100%|██████████| 6/6 [00:00<00:00, 534.00it/s]


train_loss=0.7650468945503235, eval_loss=0.7699860632419586
Epoch 6


100%|██████████| 6/6 [00:00<00:00, 455.83it/s]


train_loss=0.7144858837127686, eval_loss=0.7060147821903229
Epoch 7


100%|██████████| 6/6 [00:00<00:00, 375.27it/s]


train_loss=0.6404547691345215, eval_loss=0.630584587653478
Epoch 8


100%|██████████| 6/6 [00:00<00:00, 552.88it/s]


train_loss=0.530470073223114, eval_loss=0.5640297830104828
Epoch 9


100%|██████████| 6/6 [00:00<00:00, 472.39it/s]


train_loss=0.5433768033981323, eval_loss=0.5273530036211014
Epoch 10


100%|██████████| 6/6 [00:00<00:00, 533.88it/s]


train_loss=0.46952179074287415, eval_loss=0.47863085071245826
Epoch 11


100%|██████████| 6/6 [00:00<00:00, 490.74it/s]


train_loss=0.40960294008255005, eval_loss=0.4506497432788213
Epoch 12


100%|██████████| 6/6 [00:00<00:00, 501.88it/s]


train_loss=0.4587779641151428, eval_loss=0.4304015090068181
Epoch 13


100%|██████████| 6/6 [00:00<00:00, 468.17it/s]


train_loss=0.2373722344636917, eval_loss=0.41323807338873547
Epoch 14


100%|██████████| 6/6 [00:00<00:00, 510.83it/s]


train_loss=0.35865360498428345, eval_loss=0.3892238487799963
Epoch 15


100%|██████████| 6/6 [00:00<00:00, 468.47it/s]


train_loss=0.33884376287460327, eval_loss=0.3642441580692927
Epoch 16


100%|██████████| 6/6 [00:00<00:00, 522.95it/s]


train_loss=0.3901904225349426, eval_loss=0.33310886720816296
Epoch 17


100%|██████████| 6/6 [00:00<00:00, 483.01it/s]


train_loss=0.2393987476825714, eval_loss=0.3287673269708951
Epoch 18


100%|██████████| 6/6 [00:00<00:00, 521.03it/s]


train_loss=0.3945012092590332, eval_loss=0.3488066171606382
Epoch 19


100%|██████████| 6/6 [00:00<00:00, 478.21it/s]


train_loss=0.18498627841472626, eval_loss=0.2955337514479955
Epoch 20


100%|██████████| 6/6 [00:00<00:00, 449.47it/s]


train_loss=0.4351308345794678, eval_loss=0.28855453679958976
Epoch 21


100%|██████████| 6/6 [00:00<00:00, 525.35it/s]


train_loss=0.33365491032600403, eval_loss=0.2609152396519979
Epoch 22


100%|██████████| 6/6 [00:00<00:00, 368.41it/s]


train_loss=0.12824343144893646, eval_loss=0.2711827233433724
Epoch 23


100%|██████████| 6/6 [00:00<00:00, 400.14it/s]


train_loss=0.3606526553630829, eval_loss=0.26824564238389337
Epoch 24


100%|██████████| 6/6 [00:00<00:00, 430.74it/s]


train_loss=0.24776965379714966, eval_loss=0.24210497240225473
Epoch 25


100%|██████████| 6/6 [00:00<00:00, 511.86it/s]


train_loss=0.17519450187683105, eval_loss=0.2312312771876653
Epoch 26


100%|██████████| 6/6 [00:00<00:00, 475.57it/s]


train_loss=0.08098450303077698, eval_loss=0.22412050515413284
Epoch 27


100%|██████████| 6/6 [00:00<00:00, 476.25it/s]


train_loss=0.2092226892709732, eval_loss=0.22347259521484372
Epoch 28


100%|██████████| 6/6 [00:00<00:00, 501.84it/s]


train_loss=0.18476051092147827, eval_loss=0.21682224422693255
Epoch 29


100%|██████████| 6/6 [00:00<00:00, 501.65it/s]


train_loss=0.10258488357067108, eval_loss=0.20797731230656305
Epoch 30


100%|██████████| 6/6 [00:00<00:00, 477.15it/s]


train_loss=0.11281606554985046, eval_loss=0.20296795790394145
Epoch 31


100%|██████████| 6/6 [00:00<00:00, 490.34it/s]


train_loss=0.13579824566841125, eval_loss=0.18629741668701172
Epoch 32


100%|██████████| 6/6 [00:00<00:00, 445.39it/s]


train_loss=0.29041314125061035, eval_loss=0.22333097582062086
Epoch 33


100%|██████████| 6/6 [00:00<00:00, 524.04it/s]


train_loss=0.1310872733592987, eval_loss=0.18735248222947123
Epoch 34


100%|██████████| 6/6 [00:00<00:00, 382.73it/s]


train_loss=0.14876219630241394, eval_loss=0.17737439150611561
Epoch 35


100%|██████████| 6/6 [00:00<00:00, 538.74it/s]


train_loss=0.06871284544467926, eval_loss=0.19761620896557966
Epoch 36


100%|██████████| 6/6 [00:00<00:00, 536.91it/s]


train_loss=0.17425422370433807, eval_loss=0.1745390420158704
Epoch 37


100%|██████████| 6/6 [00:00<00:00, 538.89it/s]


train_loss=0.04241780936717987, eval_loss=0.1848378305633863
Epoch 38


100%|██████████| 6/6 [00:00<00:00, 520.59it/s]


train_loss=0.07877369970083237, eval_loss=0.1609697074939807
Epoch 39


100%|██████████| 6/6 [00:00<00:00, 500.03it/s]


train_loss=0.08439021557569504, eval_loss=0.16858054821689922
Epoch 40


100%|██████████| 6/6 [00:00<00:00, 375.38it/s]

train_loss=0.09394534677267075, eval_loss=0.16739229733745256


Epoch 41


100%|██████████| 6/6 [00:00<00:00, 329.45it/s]


train_loss=0.14459218084812164, eval_loss=0.16430883978803953
Epoch 42


100%|██████████| 6/6 [00:00<00:00, 431.72it/s]


train_loss=0.0999724417924881, eval_loss=0.14072961732745168
Epoch 43


100%|██████████| 6/6 [00:00<00:00, 504.78it/s]


train_loss=0.1381431370973587, eval_loss=0.16377003490924835
Epoch 44


100%|██████████| 6/6 [00:00<00:00, 428.68it/s]


train_loss=0.0512627512216568, eval_loss=0.18234089699884254
Epoch 45


100%|██████████| 6/6 [00:00<00:00, 491.94it/s]


train_loss=0.012076150625944138, eval_loss=0.13788197748363018
Epoch 46


100%|██████████| 6/6 [00:00<00:00, 528.07it/s]


train_loss=0.129201278090477, eval_loss=0.1508804727345705
Epoch 47


100%|██████████| 6/6 [00:00<00:00, 515.34it/s]


train_loss=0.10870211571455002, eval_loss=0.20793517306447026
Epoch 48


100%|██████████| 6/6 [00:00<00:00, 543.14it/s]


train_loss=0.04333603382110596, eval_loss=0.1439953713367383
Epoch 49


100%|██████████| 6/6 [00:00<00:00, 545.59it/s]


train_loss=0.0952044352889061, eval_loss=0.1513841034223636
Epoch 50


100%|██████████| 6/6 [00:00<00:00, 493.18it/s]


train_loss=0.08219540119171143, eval_loss=0.2193407143155734
Epoch 51


100%|██████████| 6/6 [00:00<00:00, 440.42it/s]


train_loss=0.10310357809066772, eval_loss=0.14066076278686523
Epoch 52


100%|██████████| 6/6 [00:00<00:00, 483.00it/s]


train_loss=0.13145989179611206, eval_loss=0.1928517147898674
Epoch 53


100%|██████████| 6/6 [00:00<00:00, 514.99it/s]


train_loss=0.07923197746276855, eval_loss=0.15512137937669954
Epoch 54


100%|██████████| 6/6 [00:00<00:00, 463.93it/s]


train_loss=0.07102041691541672, eval_loss=0.17006146721541882
Epoch 55


100%|██████████| 6/6 [00:00<00:00, 487.19it/s]


train_loss=0.14749157428741455, eval_loss=0.13215646202055115
Epoch 56


100%|██████████| 6/6 [00:00<00:00, 430.46it/s]


train_loss=0.021746212616562843, eval_loss=0.1544017524768909
Epoch 57


100%|██████████| 6/6 [00:00<00:00, 477.99it/s]


train_loss=0.01877804845571518, eval_loss=0.18173076833287877
Epoch 58


100%|██████████| 6/6 [00:00<00:00, 356.00it/s]


train_loss=0.015736132860183716, eval_loss=0.14005238314469654
Epoch 59


100%|██████████| 6/6 [00:00<00:00, 470.32it/s]


train_loss=0.03702063485980034, eval_loss=0.1730415777613719
Epoch 60


100%|██████████| 6/6 [00:00<00:00, 480.20it/s]


train_loss=0.08132238686084747, eval_loss=0.184716270926098
Epoch 61


100%|██████████| 6/6 [00:00<00:00, 486.91it/s]


train_loss=0.03829716891050339, eval_loss=0.12523837744568783
Epoch 62


100%|██████████| 6/6 [00:00<00:00, 559.78it/s]


train_loss=0.04142097383737564, eval_loss=0.13461604124555984
Epoch 63


100%|██████████| 6/6 [00:00<00:00, 474.41it/s]


train_loss=0.04140567034482956, eval_loss=0.17816223359356323
Epoch 64


100%|██████████| 6/6 [00:00<00:00, 509.79it/s]


train_loss=0.04027410224080086, eval_loss=0.16912528957861167
Epoch 65


100%|██████████| 6/6 [00:00<00:00, 427.32it/s]


train_loss=0.012382823042571545, eval_loss=0.15938966341006258
Epoch 66


100%|██████████| 6/6 [00:00<00:00, 441.82it/s]


train_loss=0.01855631172657013, eval_loss=0.1681711493680874
Epoch 67


100%|██████████| 6/6 [00:00<00:00, 461.99it/s]


train_loss=0.045672912150621414, eval_loss=0.18166502146050334
Epoch 68


100%|██████████| 6/6 [00:00<00:00, 430.87it/s]


train_loss=0.038470830768346786, eval_loss=0.13686283833036822
Epoch 69


100%|██████████| 6/6 [00:00<00:00, 498.06it/s]


train_loss=0.06582798063755035, eval_loss=0.12795799101392427
Epoch 70


100%|██████████| 6/6 [00:00<00:00, 465.86it/s]


train_loss=0.14673715829849243, eval_loss=0.1844643373042345
Epoch 71


100%|██████████| 6/6 [00:00<00:00, 481.85it/s]


train_loss=0.08046389371156693, eval_loss=0.1324491628135244
Epoch 72


100%|██████████| 6/6 [00:00<00:00, 450.84it/s]


train_loss=0.09639064967632294, eval_loss=0.1788532116139928
Epoch 73


100%|██████████| 6/6 [00:00<00:00, 447.54it/s]


train_loss=0.055694594979286194, eval_loss=0.1799093394850691
Epoch 74


100%|██████████| 6/6 [00:00<00:00, 488.61it/s]


train_loss=0.010401144623756409, eval_loss=0.14332509071876606
Epoch 75


100%|██████████| 6/6 [00:00<00:00, 498.57it/s]


train_loss=0.09772881120443344, eval_loss=0.13734886391709247
Epoch 76


100%|██████████| 6/6 [00:00<00:00, 482.37it/s]


train_loss=0.03261839970946312, eval_loss=0.1548610838750998
Epoch 77


100%|██████████| 6/6 [00:00<00:00, 389.13it/s]


train_loss=0.030308235436677933, eval_loss=0.16124070746203262
Epoch 78


100%|██████████| 6/6 [00:00<00:00, 462.98it/s]


train_loss=0.04182940721511841, eval_loss=0.15725090680643916
Epoch 79


100%|██████████| 6/6 [00:00<00:00, 441.91it/s]


train_loss=0.06139617785811424, eval_loss=0.17704839911311865
Epoch 80


100%|██████████| 6/6 [00:00<00:00, 405.53it/s]


train_loss=0.013417880982160568, eval_loss=0.1845324613774816
Epoch 81


100%|██████████| 6/6 [00:00<00:00, 479.86it/s]


train_loss=0.019377099350094795, eval_loss=0.15966622127840915
Epoch 82


100%|██████████| 6/6 [00:00<00:00, 365.54it/s]


train_loss=0.019489800557494164, eval_loss=0.16019324663405618
Epoch 83


100%|██████████| 6/6 [00:00<00:00, 453.50it/s]


train_loss=0.02901817113161087, eval_loss=0.18825902199993533
Epoch 84


100%|██████████| 6/6 [00:00<00:00, 474.73it/s]


train_loss=0.018335502594709396, eval_loss=0.14823028057192764
Epoch 85


100%|██████████| 6/6 [00:00<00:00, 470.27it/s]


train_loss=0.024041036143898964, eval_loss=0.17118715401738882
Epoch 86


100%|██████████| 6/6 [00:00<00:00, 466.01it/s]


train_loss=0.007395185064524412, eval_loss=0.1506967207727333
Epoch 87


100%|██████████| 6/6 [00:00<00:00, 397.26it/s]


train_loss=0.012657131999731064, eval_loss=0.20635114559748519
Epoch 88


100%|██████████| 6/6 [00:00<00:00, 461.56it/s]


train_loss=0.022287268191576004, eval_loss=0.1748092098472019
Epoch 89


100%|██████████| 6/6 [00:00<00:00, 463.08it/s]


train_loss=0.01526022981852293, eval_loss=0.08253611500064531
Epoch 90


100%|██████████| 6/6 [00:00<00:00, 357.15it/s]


train_loss=0.016085322946310043, eval_loss=0.10744796336318056
Epoch 91


100%|██████████| 6/6 [00:00<00:00, 311.76it/s]


train_loss=0.08604583889245987, eval_loss=0.20523265190422535
Epoch 92


100%|██████████| 6/6 [00:00<00:00, 286.22it/s]


train_loss=0.03426757827401161, eval_loss=0.15075700978438059
Epoch 93


100%|██████████| 6/6 [00:00<00:00, 426.91it/s]


train_loss=0.03369913622736931, eval_loss=0.1704843077265347
Epoch 94


100%|██████████| 6/6 [00:00<00:00, 364.85it/s]


train_loss=0.036706019192934036, eval_loss=0.21985420848553383
Epoch 95


100%|██████████| 6/6 [00:00<00:00, 387.40it/s]


train_loss=0.041352529078722, eval_loss=0.18190667017673454
Epoch 96


100%|██████████| 6/6 [00:00<00:00, 424.37it/s]


train_loss=0.0367666557431221, eval_loss=0.17381884297356007
Epoch 97


100%|██████████| 6/6 [00:00<00:00, 463.51it/s]


train_loss=0.03559795394539833, eval_loss=0.20853568225478133
Epoch 98


100%|██████████| 6/6 [00:00<00:00, 368.10it/s]


train_loss=0.0863896831870079, eval_loss=0.20358683619027335
Epoch 99


100%|██████████| 6/6 [00:00<00:00, 467.94it/s]


train_loss=0.013421072624623775, eval_loss=0.1702089048922062
Epoch 100


100%|██████████| 6/6 [00:00<00:00, 468.79it/s]


train_loss=0.00042473713983781636, eval_loss=0.19818038462350768
Epoch 101


100%|██████████| 6/6 [00:00<00:00, 407.34it/s]


train_loss=0.001974329585209489, eval_loss=0.1762608167094489
Epoch 102


100%|██████████| 6/6 [00:00<00:00, 428.77it/s]


train_loss=0.049881577491760254, eval_loss=0.15364081187484163
Epoch 103


100%|██████████| 6/6 [00:00<00:00, 405.22it/s]


train_loss=0.06928111612796783, eval_loss=0.24093415588140488
Epoch 104


100%|██████████| 6/6 [00:00<00:00, 480.14it/s]


train_loss=0.09502916038036346, eval_loss=0.18089723328982169
Epoch 105


100%|██████████| 6/6 [00:00<00:00, 446.37it/s]


train_loss=0.04235367849469185, eval_loss=0.1517650152090937
Epoch 106


100%|██████████| 6/6 [00:00<00:00, 441.88it/s]


train_loss=0.007399662863463163, eval_loss=0.2520640677345606
Epoch 107


100%|██████████| 6/6 [00:00<00:00, 463.24it/s]


train_loss=0.01979328691959381, eval_loss=0.20304740522988143
Epoch 108


100%|██████████| 6/6 [00:00<00:00, 439.20it/s]


train_loss=0.0006723920814692974, eval_loss=0.17772429743005583
Epoch 109


100%|██████████| 6/6 [00:00<00:00, 456.76it/s]


train_loss=0.034746818244457245, eval_loss=0.2462484093072514
Epoch 110


100%|██████████| 6/6 [00:00<00:00, 441.49it/s]


train_loss=0.01309821754693985, eval_loss=0.16878943735112747
Epoch 111


100%|██████████| 6/6 [00:00<00:00, 386.36it/s]


train_loss=0.07891824096441269, eval_loss=0.1594804752579269
Epoch 112


100%|██████████| 6/6 [00:00<00:00, 369.79it/s]


train_loss=0.038817569613456726, eval_loss=0.21296273870393634
Epoch 113


100%|██████████| 6/6 [00:00<00:00, 442.77it/s]


train_loss=0.053624942898750305, eval_loss=0.22249093019248295
Epoch 114


100%|██████████| 6/6 [00:00<00:00, 453.98it/s]


train_loss=0.004516646731644869, eval_loss=0.15376102551817894
Epoch 115


100%|██████████| 6/6 [00:00<00:00, 393.48it/s]


train_loss=0.02680881693959236, eval_loss=0.1797195767285302
Epoch 116


100%|██████████| 6/6 [00:00<00:00, 414.47it/s]


train_loss=0.00773759838193655, eval_loss=0.24054691859055313
Epoch 117


100%|██████████| 6/6 [00:00<00:00, 429.66it/s]


train_loss=0.019035564735531807, eval_loss=0.1968627599999309
Epoch 118


100%|██████████| 6/6 [00:00<00:00, 384.94it/s]


train_loss=0.03329707682132721, eval_loss=0.19019937848982713
Epoch 119


100%|██████████| 6/6 [00:00<00:00, 423.72it/s]


train_loss=0.006780736614018679, eval_loss=0.2168731758526216
Epoch 120


100%|██████████| 6/6 [00:00<00:00, 425.14it/s]


train_loss=0.00045822220272384584, eval_loss=0.15971090722208223
Epoch 121


100%|██████████| 6/6 [00:00<00:00, 445.60it/s]


train_loss=0.004078234545886517, eval_loss=0.25925194813559455
Epoch 122


100%|██████████| 6/6 [00:00<00:00, 414.19it/s]


train_loss=0.0022876074071973562, eval_loss=0.21497301493460935
Epoch 123


100%|██████████| 6/6 [00:00<00:00, 443.54it/s]


train_loss=0.0029136743396520615, eval_loss=0.15057289906932664
Epoch 124


100%|██████████| 6/6 [00:00<00:00, 451.11it/s]


train_loss=0.10473541915416718, eval_loss=0.18230268987827
Epoch 125


100%|██████████| 6/6 [00:00<00:00, 421.47it/s]


train_loss=0.002620518207550049, eval_loss=0.26360311811246595
Epoch 126


100%|██████████| 6/6 [00:00<00:00, 436.27it/s]


train_loss=0.014010801911354065, eval_loss=0.1878202120618274
Epoch 127


100%|██████████| 6/6 [00:00<00:00, 397.17it/s]


train_loss=0.002487814286723733, eval_loss=0.20322097729270658
Epoch 128


100%|██████████| 6/6 [00:00<00:00, 394.91it/s]

train_loss=0.013935196213424206, eval_loss=0.28226865905647475
